AWSTemplateFormatVersion: '2010-09-09'
Description: |
  VPC + Private Subnet + RDS PostgreSQL in private subnet

Parameters:
  DBUsername:
    Type: String
    Default: postgres
    Description: Master username for the PostgreSQL RDS instance
  DBPassword:
    Type: String
    NoEcho: true
    Description: Master password for RDS
  DBName:
    Type: String
    Default: mydatabase
    Description: Initial database name
  DBAllocatedStorage:
    Type: Number
    Default: 20
    Description: Allocated storage (GiB)

Resources:

  # 1. VPC
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: myVPC

  # 2. Private Subnet
  MyPrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: us-east-1a
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: myPrivateSubnet

  MyPrivateSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: us-east-1b
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: myPrivateSubnetB

  # 3. Security Group for RDS
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow PostgreSQL access from within VPC
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 10.0.0.0/16

  # 4. DB Subnet Group (must include at least 1—but RDS recommends 2)
  MyDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnets for RDS
      SubnetIds:
        - !Ref MyPrivateSubnet
        - !Ref MyPrivateSubnetB


  # 5. RDS PostgreSQL Instance
  MyPostgresDB:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: postgres
      EngineVersion: '14.18'             # or choose any supported version
      DBInstanceClass: db.t3.micro
      AllocatedStorage: !Ref DBAllocatedStorage
      StorageType: gp2
      PubliclyAccessible: false
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBName: !Ref DBName
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      DBSubnetGroupName: !Ref MyDBSubnetGroup
      MultiAZ: false
      DeletionProtection: false

Outputs:
  VpcId:
    Description: The ID of the VPC
    Value: !Ref MyVPC

  PrivateSubnetId:
    Description: The ID of the private subnet
    Value: !Ref MyPrivateSubnet

  DBEndpoint:
    Description: The PostgreSQL endpoint (DNS)
    Value: !GetAtt MyPostgresDB.Endpoint.Address

  DBPort:
    Description: The PostgreSQL listener port
    Value: !GetAtt MyPostgresDB.Endpoint.Port
