AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Sample CloudFormation template to create a Secrets Manager secret
  with an auto‑generated password.

Parameters:
  SecretName:
    Type: String
    Default: my-db-credentials
    Description: Friendly name for the secret
  DBUsername:
    Type: String
    Default: admin
    Description: The database master username

Resources:
  MyDBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      # Name is valid as a creation property
      Name: !Ref SecretName
      Description: "Credentials for MyDatabase"
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username":"${DBUsername}"}'
        GenerateStringKey: password
        PasswordLength: 16
        ExcludeCharacters: '"@/\\'
      Tags:
        - Key: Application
          Value: DemoApp

Outputs:
  SecretArn:
    Description: ARN of the newly created secret
    Value: !Ref MyDBSecret

  SecretNameOut:
    Description: The friendly name you gave the secret
    Value: !Ref SecretName
